version: '3'

services:
  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: notes
      POSTGRES_USER: notes
      POSTGRES_PASSWORD: notes
    volumes:
      - "db:/var/lib/postgresql/data"

  clickhouse:
    image: clickhouse/clickhouse-server:22.9.7.34-alpine
    ports:
      - 8123:8123
      - 9000:9000
    ulimits:
      nofile:
        soft: 262114
        hard: 262114
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - clickhouse_logs:/var/lib/clickhouse-server



volumes:
  db:
  clickhouse_data:
  clickhouse_logs: