# Generated by Django 4.1.4 on 2022-12-28 19:07

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name="counter",
            name="link",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterModelTable(
            name="user",
            table="web_user",
        ),
    ]
