# Generated by Django 4.1.7 on 2023-02-24 19:53

from django.db import migrations
import web.models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0002_alter_user_managers_alter_counter_link_and_more"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", web.models.UserManager()),
            ],
        ),
    ]
