# Generated by Django 4.1.7 on 2023-03-01 21:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0003_alter_user_managers"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="counter",
            options={"verbose_name": "Счетчик", "verbose_name_plural": "Счетчики"},
        ),
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "Пользователь", "verbose_name_plural": "Пользователи"},
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("admin", "Администратор"), ("staff", "Сотрудник"), ("user", "Пользователь")],
                default="user",
                max_length=15,
            ),
        ),
    ]
