# Generated by Django 4.1.7 on 2023-04-06 08:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0004_alter_counter_options_alter_user_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="counter",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="counters", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
